### ISSUE TITLE
Icon

### ISSUE THREAD

**Issue by MasterOfTheTiger** [heb12/heb12-desktop#11]
We need a new icon that represents the Bible and Heb12. It needs to be built from scratch. Our current one is a placeholder.

**Comment by amazinigmech2418** [comment]
A start...
![heb12 start](https://user-images.githubusercontent.com/33498997/39271708-c3e6a800-48a7-11e8-98ad-56e9457a8440.png)

**Comment by MasterOfTheTiger** [comment]
A *start*. I was thinking of an icon, and it has to have something related to the Bible.

**Comment by amazinigmech2418** [comment]
@MasterOfTheTiger I know. This is just the base. I used MS Paint to make it. We can use it to add stuff onto. I can't access clipart from paint, so I don't know how to get a Bible-related image on there.

**Comment by MasterOfTheTiger** [comment]
I really think it should be made from scratch, not with clipart. Maybe we can make a request post in the Scratch requests forums for it.

**Comment by amazinigmech2418** [comment]
OK. That would work!

**Comment by MasterOfTheTiger** [comment]
Here is something we could post in the requests forum:

Title: Heb12 Bible Apps logo order | Make a logo for our Bible apps on desktop and mobile

```
[center][big]Heb12 Bible Apps Logo Order[/big][/center]

Heb12 Bible apps is having a logo contest. If we choose your logo it will be displayed on our website, and on all of our apps. 

Requirements:
- Must be fully made by you
- Must have something to do with the Bible
- Must be 500 by 500 pixels in size
- Must contain the text Heb12

[quote]
Username: 
Logo image and link:
Is it 100% unique? 
What program did you use to make this? 

By entering you are giving us full rights over the logo.  
[/quote]

Copy and paste the quoted text and post it answering all of the questions.


Go to [url=http://Heb12.ml]our website[/url] for more information about Heb12 Bible Apps. 

```

Edit it as you see fit.

**Comment by MasterOfTheTiger** [comment]
I have posted it @amazinigmech2418 ! https://scratch.mit.edu/discuss/topic/305524/

**Comment by MasterOfTheTiger** [comment]
We got a logo. Tell me what you think @amazinigmech2418  

![heb12](https://user-images.githubusercontent.com/16640496/42524281-e3f35e46-8424-11e8-953d-c068aa0ab52a.png)

**Comment by amazinigmech2418** [comment]
@MasterOfTheTiger It's great!
