### ISSUE TITLE
Get CORS working for NET Bible link

### ISSUE THREAD

**Issue by MasterOfTheTiger** [heb12/heb12-desktop#14]
We need to figure out how to connect to the NET Bible API via CORS. Heb12 Desktop does fine without it, but the website does not. 

In place of the NET scripture is this message:
`Missing required request header. Must specify one of: origin,x-requested-with`

**Comment by MasterOfTheTiger** [comment]
It is temporally fixed with 7eeea79e3e4c20c5d4ffc693d57defd1cc5b43ba.

**Comment by edxtech** [comment]
Sorry for my inactivity.
Add header to the request:
origin: https://heb12.github.io

**Comment by MasterOfTheTiger** [comment]
Well, this does not effect heb12-desktop, so this should be closed.
