### ISSUE TITLE
Problems with Electron 2.0.0 or Greater on Windows

### ISSUE THREAD

**Issue by MasterOfTheTiger** [heb12/heb12-desktop#22]
Whenever the Electron version in package.json is set to 2.0.0 or newer, the program returns this message when trying to start:
```
The procedure entry point uscript_getScript_58 could not be located in the dynamic link library C:\Users\USERNAME\AppData\Local\Programs\heb12\Heb12 Bible.exe.
```
![capture](https://user-images.githubusercontent.com/16640496/42243646-dfd564e8-7ec6-11e8-8fca-dcf67ba53ee9.PNG)

I have tried changing versions and it only works with the 1.8 series. It always returns that message when it uses Electron 2.0.0 or newer. 

The current Windows .exe installer uses Electron version 1.8.7 because any newer does not work. I could find no existing issues reported in the [Electron GitHub repo](https://github.com/electron/electron), so I reported it here: https://github.com/electron/electron/issues/13553.

This is a very important issue. It needs to be fixed as soon as possible.

**Comment by amazinigmech2418** [comment]
Enable online alpha and it will be fine.

**Comment by MasterOfTheTiger** [comment]
What do you mean? Soon I am going to be deleting gh-pages in favor for a PHP version.

**Comment by amazinigmech2418** [comment]
@MasterOfTheTiger The online alpha is a way that anyone can access Heb12 on any device without the need for server-side communications.

**Comment by MasterOfTheTiger** [comment]
Note: this also affects 3.0.x, but it doesn't seem to affect version 2.0.11

**Comment by MasterOfTheTiger** [comment]
This whole thing was a mess, but I found out the problem has something to do with the computer on which I was building the package.
