### ISSUE TITLE
Use electron-store module instead of localStorage

### ISSUE THREAD

**Issue by MasterOfTheTiger** [heb12/heb12-desktop#23]
I would like to switch things over to https://github.com/sindresorhus/electron-store instead of localStorage for reasons mentioned here: https://github.com/sindresorhus/electron-store/issues/17

**Comment by amazinigmech2418** [comment]
We shouldn't use it for the online part.

**Comment by MasterOfTheTiger** [comment]
No we should not. You are right. However, I am planning a completely new online version built with PhP.

**Comment by MasterOfTheTiger** [comment]
This is done in commit 179bcdfb914bfc0c9d34a9452cd65eba70696871. All data previously used by people will be deleted when they run the new version. This is no big deal for two reasons:
1. We are in 0.x still
1. There is no information that is hard to reobtain
1. We have no users to affect
