### ISSUE TITLE
Online Alpha is Down

### ISSUE THREAD

**Issue by amazinigmech2418** [heb12/heb12-desktop#24]
**Describe the bug**
Online Alpha doesn't work

**To Reproduce**
heb12.ml/heb12

**Expected behavior**
It should start online alpha.

**Screenshots**
none needed

**Desktop (please complete the following information):**
Not needed (about online alpha)

**Additional context**
none

**Comment by MasterOfTheTiger** [comment]
This is a change in GitHub pages' behaviour. It will be fixed in a few minutes.

**Comment by MasterOfTheTiger** [comment]
Fixed here: https://github.com/heb12/heb12.github.io/commit/0aefb45ca48f707601a6f453f132dfe7dd08fd47

**Comment by MasterOfTheTiger** [comment]
Nevermind. The problem is I renamed the repo. Well, online alpha will be taken down soon anyway. I will push my changes for heb12web soon.

**Comment by MasterOfTheTiger** [comment]
New link: https://heb12.ml/heb12-desktop

**Comment by amazinigmech2418** [comment]
OK.

**Comment by amazinigmech2418** [comment]
Why will online alpha be taken down? I think it should be made into another repo based on preference for server-side communications.

**Comment by MasterOfTheTiger** [comment]
Online alpha has a new link. It uses PHP now. The other version never worked very well and this will be better.

**Comment by MasterOfTheTiger** [comment]
Here is the link for the PHP version: https://github.com/heb12/heb12web. I made it myself.

**Comment by amazinigmech2418** [comment]
@MasterOfTheTiger I prefer the UI for the current one. The PHP version seems a little tricky to use.

**Comment by MasterOfTheTiger** [comment]
It is very subject to change. This is a rough example of what it will end up as.
