### ISSUE TITLE
.exe compilation looks suspicious

### ISSUE THREAD

**Issue by amazinigmech2418** [heb12/heb12-desktop#6]
Edit by MasterOfTheTiger: Old title ".exe compilation contains virus based on McAfee"

**Comment by MasterOfTheTiger** [comment]
You beat me to making this issue :P. I noticed this when installing it on my grandma’s computer. I could not even get it to install. I don’t know how to fix it. Do you have any ideas?

**Comment by MasterOfTheTiger** [comment]
I could not find anything on McAfee's website that would help us. I could not even find an email address that would help.

**Comment by edxtech** [comment]
See https://kc.mcafee.com/corporate/index?page=content&id=KB85567

**Comment by MasterOfTheTiger** [comment]
@edxtech Thanks! I will look into it.

**Comment by edxtech** [comment]
It's the same email for both, I think..?

**Comment by MasterOfTheTiger** [comment]
I guess I can see about updating it. It should not be hard at all. Hopefully that fixes it.

**Comment by MasterOfTheTiger** [comment]
I set the new version of Electron to 1.8.4 (the newest besides the 2.0.0 betas). Can someone make an exe file and test it?

**Comment by MasterOfTheTiger** [comment]
Here are some of the things I have run into when downloading and installing the .exe:

1. Chrome says that it has not been downloaded often and could be dangerous
2. Windows asks you if you are sure you want to run the file because it looks suspicious.
3. If you are using McAfee then shortly after you install it a notice from then will pop up saying that the file looks malicious and has been quarantined

**Comment by edxtech** [comment]
This is the same with any file. They are reported as suspicious until they have been downloaded and ran enough times.

**Comment by MasterOfTheTiger** [comment]
@edxtech So we make a bot that downloads it over and over and over again. Great idea.

So, what do we actually do about it?

**Comment by MasterOfTheTiger** [comment]
I checked it out on virustotal.com and only one antivirus tripped up on it, and it was not McAfee.

**Comment by MasterOfTheTiger** [comment]
Confirmed for version 0.2.0 and over.

**Comment by MasterOfTheTiger** [comment]
I think the best way to fix this is to sign the code. It is expensive, but when this project gets bigger, we will need it.

**Comment by MasterOfTheTiger** [comment]
Any news on this @amazinigmech2418?

**Comment by amazinigmech2418** [comment]
No news currently. I haven't actually had much time to work on this lately.

**Comment by MasterOfTheTiger** [comment]
> No news currently. I haven't actually had much time to work on this lately.

I know, but would you mind re-testing this with Heb12 Desktop 0.3.0?

**Comment by amazinigmech2418** [comment]
All good!

**Comment by MasterOfTheTiger** [comment]
@amazinigmech2418 Do you think we can close it then?

**Comment by amazinigmech2418** [comment]
I think so.
