### ISSUE TITLE
Make CaV not use Node exports

### ISSUE THREAD

**Issue by amazinigmech2418** [heb12/heb12-desktop#8]
https://github.com/heb12/heb12/blob/4fffad540a2f927ed458d2b0d6e5fbe18e261428/app/CaV/js/cv.js#L96

**Comment by MasterOfTheTiger** [comment]
Why? What is wrong with this? How does this interfere with the program?

**Comment by amazinigmech2418** [comment]
It won't load in gh-pages. It can't read from CaV with modules.

**Comment by MasterOfTheTiger** [comment]
@amazinigmech2418 Hmmm. I am not sure if we can fix this.

**Comment by MasterOfTheTiger** [comment]
I am looking at it now and I am going to try it
